'use client'
import {useEffect,useState} from 'react'

type Position={symbol:string,qty:number,market_value:number,avg_entry_price:number,unrealized_pl:number}
type Account={equity:string,buying_power:string,cash:string}
export default function Home(){const [email,setEmail]=useState('demo@example.com');const [password,setPassword]=useState('password123');const [logged,setLogged]=useState(false);const [account,setAccount]=useState<Account|null>(null);const [positions,setPositions]=useState<Position[]>([]);const [symbol,setSymbol]=useState('AAPL');const [quote,setQuote]=useState<any>(null);const [qty,setQty]=useState('1');const [msg,setMsg]=useState('');
async function refresh(){const a=await fetch('/api/portfolio');if(a.ok){const j=await a.json();setAccount(j.account);setLogged(true)}const p=await fetch('/api/positions');if(p.ok)setPositions((await p.json()).positions||[])}
useEffect(()=>{refresh()},[])
async function login(){let r=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});if(!r.ok){r=await fetch('/api/auth/signup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})})}if(r.ok){setMsg('');refresh()}else setMsg((await r.json()).error||'Authentication failed')}
async function getQuote(){const r=await fetch('/api/quote?symbol='+encodeURIComponent(symbol));const j=await r.json();if(r.ok)setQuote(j);else setMsg(j.error||'Quote failed')}
async function order(side:string){const r=await fetch('/api/order',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({symbol,side,qty:Number(qty)})});const j=await r.json();setMsg(r.ok?'Order submitted: '+j.order.id:(j.error||'Order failed'));if(r.ok){refresh();getQuote()}}
if(!logged)return <main className="shell"><div className="card" style={{maxWidth:430,margin:'12vh auto'}}><div className="brand">Robinhood Clone</div><p className="muted">Paper trading with a real backend.</p><div className="stack"><input className="input" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email"/><input className="input" type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password"/><button className="btn" onClick={login}>Sign in / create account</button>{msg&&<small>{msg}</small>}</div></div></main>
return <main className="shell"><header className="top"><div className="brand">Robinhood Clone</div><button className="btn secondary" onClick={async()=>{await fetch('/api/auth/logout',{method:'POST'});location.reload()}}>Log out</button></header><div className="grid"><section className="card"><div className="muted">Portfolio value</div><div className="value">${Number(account?.equity||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}</div><div className="row muted"><span>Cash ${Number(account?.cash||0).toLocaleString()}</span><span>Buying power ${Number(account?.buying_power||0).toLocaleString()}</span></div><hr/><h3>Positions</h3><div className="list">{positions.length?positions.map(p=><div className="item" key={p.symbol}><b>{p.symbol}</b><span>{Number(p.qty).toFixed(4)} · ${Number(p.market_value).toFixed(2)}</span></div>):<div className="muted">No positions yet.</div>}</div></section><aside className="card"><h3>Trade</h3><div className="stack"><input className="input" value={symbol} onChange={e=>setSymbol(e.target.value.toUpperCase())}/><button className="btn secondary" onClick={getQuote}>Get quote</button>{quote&&<div><div className="quote">${Number(quote.price).toFixed(2)}</div><div className="muted">{quote.symbol}</div></div>}<input className="input" value={qty} onChange={e=>setQty(e.target.value)} type="number" min="0.0001" step="0.0001"/><div className="row"><button className="btn buy" onClick={()=>order('buy')}>Buy</button><button className="btn sell" onClick={()=>order('sell')}>Sell</button></div>{msg&&<small>{msg}</small>}</div></aside></div></main>}
